const fs=require('fs');
const path=require('path');
const vm=require('vm');
const api=fs.readFileSync(path.join(__dirname,'..','api','naver-datalab.js'),'utf8');
const html=fs.readFileSync(path.join(__dirname,'..','index.html'),'utf8');
function assert(ok,msg){if(!ok) throw new Error(msg);}
assert(api.includes("naverapihub.apigw.ntruss.com/search-trend/v1/search"),'DataLab API HUB endpoint missing');
assert(api.includes("naveropenapi.apigw.ntruss.com/datalab/v1/search"),'DataLab API HUB compatibility endpoint missing');
assert(api.includes('NAVER_DATALAB_CLIENT_ID')&&api.includes('NAVER_DATALAB_CLIENT_SECRET'),'DataLab env vars missing');
assert(api.includes("'X-NCP-APIGW-API-KEY-ID'")&&api.includes("'X-NCP-APIGW-API-KEY'"),'DataLab API HUB headers missing');
assert(api.includes('keywordGroups')&&api.includes('timeUnit'),'DataLab request payload missing');
assert(api.includes("req.method!=='POST'")&&api.includes('401'),'DataLab auth guard missing');
assert(html.includes('/api/naver-datalab'),'Keyword screen does not call DataLab');
assert(html.includes('datalab-trend-card')&&html.includes('검색 관심도 추이'),'DataLab trend UI missing');
assert(html.includes('runSingleDataLabSearch'),'Single keyword mode must have a dedicated DataLab-first search flow');
assert(html.includes("addEventListener('click',runSingleDataLabSearch,true)"),'Single keyword search must intercept the Search Ads result flow');
assert(html.includes('id="datalab-time-unit"')&&html.includes('id="datalab-start-date"')&&html.includes('id="datalab-end-date"'),'DataLab period controls missing');
assert(html.includes('datalab-summary-card'),'DataLab single result summary missing');
assert(html.includes('function estimateKeywordVolumes('),'Estimated volume helper missing');
assert(html.includes("Promise.all([fetch('/api/naver-keyword'"),'Single keyword mode must combine Keyword Tool and DataLab');
assert(html.includes('월간 예상 검색량')&&html.includes('일평균 예상 검색량'),'Estimated-volume summary labels missing');
assert(html.includes('period-volume-table'),'Estimated period-volume table missing');
assert(html.includes('키워드 도구 월간 검색량과 데이터랩 상대 추이를 조합한 추정치'),'Estimate disclosure missing');
assert(/function syncMode\(\)[\s\S]*?datalab-controls[\s\S]*?bulkMode\|\|relatedMode/.test(html),'Mode sync must hide DataLab date controls outside the single-keyword tab');
assert(html.includes('<option value="year">연간</option>'),'Annual graph filter missing');
assert(html.includes('function setDataLabDefaultRange('),'Automatic period range helper missing');
assert(html.includes('function localInputDate('),'Local calendar date helper missing');
assert(html.includes("unit==='year'?5*365:unit==='month'?365:unit==='week'?183:30"),'Expected automatic ranges are not configured');
assert(html.includes('datalab-chart-tooltip'),'Interactive chart tooltip missing');
assert(html.includes("addEventListener('mouseenter'")&&html.includes("addEventListener('touchstart'"),'Mouse and touch tooltip handlers missing');
const estimatorSource=html.match(/function estimateKeywordVolumes\([\s\S]*?\n    \}/);
assert(estimatorSource,'Estimator source could not be extracted');
const sandbox={};vm.runInNewContext(estimatorSource[0],sandbox);
const estimates=sandbox.estimateKeywordVolumes(3000,[{period:'2026-08-01',ratio:25},{period:'2026-08-02',ratio:75}],'2026-08-01','2026-08-30');
assert(estimates.length===2,'Estimator must preserve every trend period');
assert(Math.abs(estimates[1].estimate-estimates[0].estimate*3)<=1,'Estimator must distribute volume in proportion to DataLab ratios within rounding tolerance');
assert(estimates.reduce((sum,item)=>sum+item.estimate,0)===Math.round(3000*(30/30.4375)),'Estimator total must match the date-range-scaled monthly volume');
console.log('naver-datalab.test.js: ok');
